authorize_check_query = "\
        SELECT id, username, attribute, value, op \
        FROM ${authcheck_table} \
        WHERE username = '%{SQL-User-Name}' \
        ORDER BY id"

authorize_reply_query = "\
        SELECT id, username, attribute, value, op \
        FROM ${authreply_table} \
        WHERE username = '%{SQL-User-Name}' \
        ORDER BY id"

group_membership_query = "\
        SELECT groupname \
        FROM ${usergroup_table} \
        WHERE username = '%{SQL-User-Name}' \
        ORDER BY priority"

authorize_group_check_query = "\
        SELECT id, groupname, attribute, value, op \
        FROM ${groupcheck_table} \
        WHERE groupname = '%{${group_attribute}}' \
        ORDER BY id"

authorize_group_reply_query = "\
        SELECT id, groupname, attribute, value, op \
        FROM ${groupreply_table} \
        WHERE groupname = '%{${group_attribute}}' \
        ORDER BY id"

post-auth_query = "\
        INSERT INTO ${postauth_table} \
        (username, pass, reply, authdate) \
        VALUES ('%{SQL-User-Name}', \
        '%{%{User-Password}:-%{Chap-Password}}', \
        '%{reply:Packet-Type}', '%S')"

accounting_start_query = "\
        INSERT INTO ${acct_table1} \
        (acctsessionid, acctuniqueid, username, nasipaddress, nasportid, \
        nasporttype, acctstarttime, acctauthentic, framedipaddress, \
        acctinputoctets, acctoutputoctets, servicetype, framedprotocol) \
        VALUES ('%{Acct-Session-Id}', '%{Acct-Unique-Session-Id}', \
        '%{SQL-User-Name}', '%{NAS-IP-Address}', '%{NAS-Port-Id}', \
        '%{NAS-Port-Type}', FROM_UNIXTIME(%{integer:Event-Timestamp}), \
        '%{Acct-Authentic}', '%{Framed-IP-Address}', '0', '0', \
        '%{Service-Type}', '%{Framed-Protocol}')"

accounting_update_query = "\
        UPDATE ${acct_table1} \
        SET framedipaddress = '%{Framed-IP-Address}', \
        acctsessiontime = '%{integer:Acct-Session-Time}', \
        acctinputoctets = '%{integer:Acct-Input-Octets}', \
        acctoutputoctets = '%{integer:Acct-Output-Octets}' \
        WHERE acctsessionid = '%{Acct-Session-Id}' \
        AND username = '%{SQL-User-Name}' \
        AND nasipaddress = '%{NAS-IP-Address}'"

accounting_stop_query = "\
        UPDATE ${acct_table2} \
        SET acctstoptime = FROM_UNIXTIME(%{integer:Event-Timestamp}), \
        acctsessiontime = '%{integer:Acct-Session-Time}', \
        acctinputoctets = '%{integer:Acct-Input-Octets}', \
        acctoutputoctets = '%{integer:Acct-Output-Octets}', \
        acctterminatecause = '%{Acct-Terminate-Cause}' \
        WHERE acctsessionid = '%{Acct-Session-Id}' \
        AND username = '%{SQL-User-Name}' \
        AND nasipaddress = '%{NAS-IP-Address}'"

accounting_onoff_query = "\
        UPDATE ${acct_table1} \
        SET acctstoptime = FROM_UNIXTIME(%{integer:Event-Timestamp}), \
        acctterminatecause = '%{Acct-Terminate-Cause}' \
        WHERE acctstoptime IS NULL \
        AND nasipaddress = '%{NAS-IP-Address}'"
