<?php
function regenerateRadiusClients($conn) {
    $result = $conn->query("
        SELECT nasname, shortname, secret, ip_address 
        FROM nas 
        WHERE secret IS NOT NULL AND secret != ''
        ORDER BY id
    ");

    $conf  = "# Auto-generated by ISP System — " . date('Y-m-d H:i:s') . "\n\n";
    $conf .= "client localhost {\n";
    $conf .= "    ipaddr = 127.0.0.1\n";
    $conf .= "    secret = 123456\n";
    $conf .= "    shortname = localhost\n";
    $conf .= "    require_message_authenticator = true\n";
    $conf .= "}\n\n";

    $added_ips = ['127.0.0.1'];

    while ($nas = $result->fetch_assoc()) {
        $ip     = trim($nas['ip_address'] ?: $nas['nasname']);
        $name   = preg_replace('/[^a-zA-Z0-9_]/', '_', $nas['shortname']);
        $secret = $nas['secret'];

        if (empty($ip) || !filter_var($ip, FILTER_VALIDATE_IP)) continue;
        if (in_array($ip, $added_ips)) continue;

        $added_ips[] = $ip;

        $conf .= "client {$name} {\n";
        $conf .= "    ipaddr = {$ip}\n";
        $conf .= "    secret = {$secret}\n";
        $conf .= "    shortname = {$name}\n";
        $conf .= "    require_message_authenticator = false\n";
        $conf .= "}\n\n";
    }

    // Shared volume — isp_app ও isp_radius দুটোই এই path দেখে
    $path = '/var/www/html/radius/config/clients.conf';
    if (!is_dir(dirname($path))) mkdir(dirname($path), 0755, true);
    file_put_contents($path, $conf);
    chmod($path, 0644);

    // RADIUS reload
    shell_exec("kill -HUP 1 2>/dev/null");
    return true;
}
?>
